name = "IkerCraft: Aeronautics"
author = "Ivan"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c69b8a72413601f2a7c303b5851dfa21347ee60c766c9cb1f9119d635934493c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"

[options]
