name = "IkerCraft: Aeronautics"
author = "Ivan"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ce9d4d2199e7f6c744c1c3de2aa3f74334c33690619d45db117cffebc4a728d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"

[options]
