name = "IkerCraft: Aeronautics"
author = "Ivan"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "82c06c7c84141d238816a2e0dedca1f16df9ab64f9557ba013a2fed88dceb5f9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"

[options]
acceptable-game-versions = ["1.20.1"]
